# Generated by Django 2.1 on 2021-12-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=30, verbose_name='vocabulary')),
                ('vocab_type', models.CharField(max_length=10, verbose_name='vocab_type')),
                ('chinese', models.TextField()),
                ('audio', models.ImageField(upload_to='')),
                ('image', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete='CASCADE', to='users.User')),
            ],
        ),
    ]
