# Generated by Django 3.2.11 on 2022-01-05 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20211229_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=30, verbose_name='vocabulary')),
                ('vocab_type', models.CharField(max_length=10, verbose_name='vocab_type')),
                ('chinese', models.TextField()),
                ('audio', models.ImageField(upload_to='audio/')),
                ('image', models.ImageField(upload_to='images/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Learningweb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webname', models.CharField(max_length=30, verbose_name='webname')),
                ('webaddr', models.CharField(max_length=100, verbose_name='webaddr')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
