# Generated by Django 3.2.11 on 2022-01-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningweb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
