# Generated by Django 3.2.11 on 2022-01-10 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0002_auto_20220107_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
