# Generated by Django 2.1 on 2021-12-23 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0002_auto_20211223_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocab',
            old_name='user_id',
            new_name='user',
        ),
    ]
