# Generated by Django 3.2.11 on 2022-01-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0003_vocab_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='review_cycle',
            field=models.CharField(default='0', max_length=9999, verbose_name='review_cycle'),
        ),
    ]
