# Generated by Django 2.1 on 2021-12-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0004_auto_20211223_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocab',
            name='user',
            field=models.ForeignKey(null=True, on_delete='models.CASCADE', to='users.User'),
        ),
    ]
